asf_product_homepage:
    path: /
    defaults: { _controller: "ASFProductBundle:Default:index" }
    
asf_product_product:
    prefix: /product
    resource: "@ASFProductBundle/Resources/config/routing/product.yml"
    
asf_product_category:
    prefix: /product-category
    resource: "@ASFProductBundle/Resources/config/routing/category.yml"
    
asf_product_ajax_request:
    prefix: /ajax
    resource: "@ASFProductBundle/Resources/config/routing/ajax_request.yml"
    
asf_product_doc:
    prefix: /doc
    resource: "@ASFProductBundle/Resources/config/routing/doc.yml"